#### **7. `.github/workflows/run.yml`**
This file sets up a **GitHub Action** to automatically run your Hausa programs when you push code to the repository.

```yaml
# .github/workflows/run.yml
name: Run Hausa Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ply

      - name: Run Hausa program
        run: |
          python cli.py examples/hello.hausa
