# .github/workflows/run.yml
name: Run Hausa Program

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job to run
jobs:
  run:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies (PLY for lexer and parser)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ply

      # Step 4: Run the Hausa program
      - name: Run Hausa program
        run: |
          echo "Running Hausa program..."
          python cli.py examples/hello.hausa

      # Step 5: (Optional) Add a step to validate the output
      - name: Validate output
        run: |
          OUTPUT=$(python cli.py examples/hello.hausa)
          if [[ "$OUTPUT" == *"Barka da zuwa zuwa harshen shirye-shiryen Hausa!"* ]]; then
            echo "Output is correct!"
          else
            echo "Output is incorrect!"
            exit 1
          fi
